# Web_Scraping

In [1]:
# importamos librerias
import pandas as pd 
from bs4 import BeautifulSoup
import requests

por medio de web_scraping recopilamos datos desde wikipedia para tener una estimacion de la poblacion en el año 2021, que coincide con el ultimo año de nuestro dataset original

In [2]:
direc_scraping='https://es.wikipedia.org/wiki/Anexo:Comunas_de_la_ciudad_de_Buenos_Aires_por_poblaci%C3%B3n'
request= requests.get(direc_scraping)
soup= BeautifulSoup(request.text, 'html.parser')
paginas= pd.read_html(direc_scraping)
paginas[0]

   Evolución demográfica e histórica de los habitantes de las Comunas de la Ciudad Autónoma de Buenos Aires (CABA)[1]​  \
                                                                                                         Puesto (2022)
0                                                  1°
1                                                  2°
2                                                  3°
3                                                  4°
4                                                  5°
5                                                  6°
6                                                  7°
7                                                  8°
8                                                  9°
9                                                 10°
10                                                11°
11                                                12°
12                                                13°
13                                                14°
14                                                15°
15                                              TOTAL

                                                           \
       Comuna CENSO 1991 CENSO 2001 CENSO 2010 CENSO 2022
0   Comuna 13    250 224    228 226    231 331    265 199
1   Comuna 14    256 927    225 245    225 970    249 016
2   Comuna 12    198 185    191 122    200 116    236 294
3    Comuna 4    215 223    215 046    218 245    230 945
4    Comuna 1    200 689    171 985    205 886    223 282
5    Comuna 7    198 489    197 333    220 591    216 832
6    Comuna 8    151 078    161 642    187 237    204 842
7    Comuna 6    183 740    170 309    176 076    203 784
8   Comuna 11    199 049    189 666    189 832    203 491
9   Comuna 15    195 346    183 110    182 574    197 903
10   Comuna 3    200 275    184 015    187 537    195 462
11   Comuna 5    188 342    173 769    179 005    193 859
12  Comuna 10    167 671    163 209    166 022    171 797
13   Comuna 9    161 518    155 967    161 797    169 538
14   Comuna 2    198 647    165 494    157 932    158 368
15       CABA  2 965 403  2 776 138  2 890 151  3 120 612


   Crecimiento 2010-2022 Unnamed: 7_level_1
0              + 14,64 %                NaN
1              + 10,19 %                NaN
2              + 18,07 %                NaN
3               + 5,81 %                NaN
4               + 8,44 %                NaN
5               - 1,70 %                NaN
6               + 9,40 %                NaN
7              + 15,73 %                NaN
8               + 7,19 %                NaN
9               + 8,39 %                NaN
10              + 4,22 %                NaN
11              + 8,29 %                NaN
12              + 3,47 %                NaN
13              + 4,78 %                NaN
14              + 0,27 %                NaN
15              + 7,97 %                NaN

guardamos como dataframe para utilizarlo posteriormente para uno de nuestros KPI solicitados

In [3]:
paginas[0].to_csv('data/dataset_poblacion.csv', index=False)

abrimos dataset

In [4]:
df_poblacion=pd.read_csv('data/dataset_poblacion.csv')
df_poblacion

,Evolución demográfica e histórica de los habitantes de las Comunas de la Ciudad Autónoma de Buenos Aires (CABA)[1]​,Evolución demográfica e histórica de los habitantes de las Comunas de la Ciudad Autónoma de Buenos Aires (CABA)[1]​.1,Evolución demográfica e histórica de los habitantes de las Comunas de la Ciudad Autónoma de Buenos Aires (CABA)[1]​.2,Evolución demográfica e histórica de los habitantes de las Comunas de la Ciudad Autónoma de Buenos Aires (CABA)[1]​.3,Evolución demográfica e histórica de los habitantes de las Comunas de la Ciudad Autónoma de Buenos Aires (CABA)[1]​.4,Evolución demográfica e histórica de los habitantes de las Comunas de la Ciudad Autónoma de Buenos Aires (CABA)[1]​.5,Evolución demográfica e histórica de los habitantes de las Comunas de la Ciudad Autónoma de Buenos Aires (CABA)[1]​.6,Evolución demográfica e histórica de los habitantes de las Comunas de la Ciudad Autónoma de Buenos Aires (CABA)[1]​.7
0,Puesto (2022),Comuna,CENSO 1991,CENSO 2001,CENSO 2010,CENSO 2022,Crecimiento 2010-2022,Unnamed: 7_level_1
1,1°,Comuna 13,250 224,228 226,231 331,265 199,"+ 14,64 %",NaN
2,2°,Comuna 14,256 927,225 245,225 970,249 016,"+ 10,19 %",NaN
3,3°,Comuna 12,198 185,191 122,200 116,236 294,"+ 18,07 %",NaN
4,4°,Comuna 4,215 223,215 046,218 245,230 945,"+ 5,81 %",NaN
5,5°,Comuna 1,200 689,171 985,205 886,223 282,"+ 8,44 %",NaN
6,6°,Comuna 7,198 489,197 333,220 591,216 832,"- 1,70 %",NaN
7,7°,Comuna 8,151 078,161 642,187 237,204 842,"+ 9,40 %",NaN
8,8°,Comuna 6,183 740,170 309,176 076,203 784,"+ 15,73 %",NaN
9,9°,Comuna 11,199 049,189 666,189 832,203 491,"+ 7,19 %",NaN
10,10°,Comuna 15,195 346,183 110,182 574,197 903,"+ 8,39 %",NaN
11,11°,Comuna 3,200 275,184 015,187 537,195 462,"+ 4,22 %",NaN
12,12°,Comuna 5,188 342,173 769,179 005,193 859,"+ 8,29 %",NaN
13,13°,Comuna 10,167 671,163 209,166 022,171 797,"+ 3,47 %",NaN
14,14°,Comuna 9,161 518,155 967,161 797,169 538,"+ 4,78 %",NaN
15,15°,Comuna 2,198 647,165 494,157 932,158 368,"+ 0,27 %",NaN
16,TOTAL,CABA,2 965 403,2 776 138,2 890 151,3 120 612,"+ 7,97 %",NaN

procedemos a limpiar y renombrar columnas del dataframe

In [5]:
def clean_data(df_poblacion):
    # Drop column: 'Evolución demográfica e histórica de los habitantes de las Comunas de la Ciudad Autónoma de Buenos Aires (CABA)[1]​.7'
    df_poblacion = df_poblacion.drop(columns=['Evolución demográfica e histórica de los habitantes de las Comunas de la Ciudad Autónoma de Buenos Aires (CABA)[1]\u200b.7'])
    # Rename column 'Evolución demográfica e histórica de los habitantes de las Comunas de la Ciudad Autónoma de Buenos Aires (CABA)[1]\u200b' to 'puesto (2022)'
    df_poblacion = df_poblacion.rename(columns={'Evolución demográfica e histórica de los habitantes de las Comunas de la Ciudad Autónoma de Buenos Aires (CABA)[1]\u200b': 'puesto (2022)'})
    # Rename column 'Evolución demográfica e histórica de los habitantes de las Comunas de la Ciudad Autónoma de Buenos Aires (CABA)[1]\u200b.1' to 'Comuna'
    df_poblacion = df_poblacion.rename(columns={'Evolución demográfica e histórica de los habitantes de las Comunas de la Ciudad Autónoma de Buenos Aires (CABA)[1]\u200b.1': 'Comuna'})
    # Rename column 'Evolución demográfica e histórica de los habitantes de las Comunas de la Ciudad Autónoma de Buenos Aires (CABA)[1]\u200b.2' to 'CENSO 1991'
    df_poblacion = df_poblacion.rename(columns={'Evolución demográfica e histórica de los habitantes de las Comunas de la Ciudad Autónoma de Buenos Aires (CABA)[1]\u200b.2': 'CENSO 1991'})
    # Rename column 'Evolución demográfica e histórica de los habitantes de las Comunas de la Ciudad Autónoma de Buenos Aires (CABA)[1]\u200b.3' to 'CENSO 2001'
    df_poblacion = df_poblacion.rename(columns={'Evolución demográfica e histórica de los habitantes de las Comunas de la Ciudad Autónoma de Buenos Aires (CABA)[1]\u200b.3': 'CENSO 2001'})
    # Rename column 'Evolución demográfica e histórica de los habitantes de las Comunas de la Ciudad Autónoma de Buenos Aires (CABA)[1]\u200b.4' to 'CENSO 2010'
    df_poblacion = df_poblacion.rename(columns={'Evolución demográfica e histórica de los habitantes de las Comunas de la Ciudad Autónoma de Buenos Aires (CABA)[1]\u200b.4': 'CENSO 2010'})
    # Rename column 'Evolución demográfica e histórica de los habitantes de las Comunas de la Ciudad Autónoma de Buenos Aires (CABA)[1]\u200b.5' to 'CENSO 2022'
    df_poblacion = df_poblacion.rename(columns={'Evolución demográfica e histórica de los habitantes de las Comunas de la Ciudad Autónoma de Buenos Aires (CABA)[1]\u200b.5': 'CENSO 2022'})
    # Rename column 'Evolución demográfica e histórica de los habitantes de las Comunas de la Ciudad Autónoma de Buenos Aires (CABA)[1]\u200b.6' to 'CRECIMIENTO 2010-2022'
    df_poblacion = df_poblacion.rename(columns={'Evolución demográfica e histórica de los habitantes de las Comunas de la Ciudad Autónoma de Buenos Aires (CABA)[1]\u200b.6': 'CRECIMIENTO 2010-2022'})
    # Drop column: 'CENSO 2001'
    df_poblacion = df_poblacion.drop(columns=['CENSO 2001'])
    # Drop column: 'CENSO 1991'
    df_poblacion = df_poblacion.drop(columns=['CENSO 1991'])
    return df_poblacion

df_poblacion = clean_data(df_poblacion.copy())
df_poblacion.head()

   puesto (2022)     Comuna  CENSO 2010  CENSO 2022  CRECIMIENTO 2010-2022
0  Puesto (2022)     Comuna  CENSO 2010  CENSO 2022  Crecimiento 2010-2022
1             1°  Comuna 13     231 331     265 199              + 14,64 %
2             2°  Comuna 14     225 970     249 016              + 10,19 %
3             3°  Comuna 12     200 116     236 294              + 18,07 %
4             4°   Comuna 4     218 245     230 945               + 5,81 %

In [6]:
df_poblacion.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 5 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   puesto (2022)          17 non-null     object
 1   Comuna                 17 non-null     object
 2   CENSO 2010             17 non-null     object
 3   CENSO 2022             17 non-null     object
 4   CRECIMIENTO 2010-2022  17 non-null     object
dtypes: object(5)
memory usage: 812.0+ bytes

procedemos a calcular la tasa de crecimiento anual para poder tener los datos de 2021 sobre el indice de crecimiento y poblacion total segun los resultados del censo llevado a cabo en 2022

In [7]:
# eliminamos la primer fila que contiene el titulo de las columnas
df_poblacion = df_poblacion.drop(df_poblacion.index[0])

# convertimos la columna 'CENSO 2022' a float
df_poblacion['CENSO 2022'] = df_poblacion['CENSO 2022'].str.replace('\xa0', '').astype(float)

# poblacion total de 2022
censo_2022 = 3120612

# tasa de crecimiento total entre 2010 y 2022
tasa_crecimiento_total = 7.97 / 100

# calculamos la tasa de crecimiento anual
tasa_crecimiento_anual = (1 + tasa_crecimiento_total) ** (1 / 12) - 1

# creamos una nueva columna con los valores estimados para 2021
df_poblacion['CENSO 2021'] = df_poblacion['CENSO 2022'] / (1 + tasa_crecimiento_anual)

# cambiamos tipo de dato de la columna
df_poblacion['CENSO 2021']= df_poblacion['CENSO 2021'].astype(int)

df_poblacion.head()

,puesto (2022),Comuna,CENSO 2010,CENSO 2022,CRECIMIENTO 2010-2022,CENSO 2021
1,1°,Comuna 13,231 331,265199.0,"+ 14,64 %",263509
2,2°,Comuna 14,225 970,249016.0,"+ 10,19 %",247429
3,3°,Comuna 12,200 116,236294.0,"+ 18,07 %",234788
4,4°,Comuna 4,218 245,230945.0,"+ 5,81 %",229473
5,5°,Comuna 1,205 886,223282.0,"+ 8,44 %",221859

podemos notar que ya tenemos el censo y la poblacion de las comunas para el año 2021, pero necesitamos de los datos de los demas años. con este proposito, vamos a realizar un calculo basado en la columna 'CRECIMIENTO 2010-2022', que indica el indice de crecimiento porcentaje. este factor sera esencial para el desarrollo de nuestro codigo

In [8]:
# datos de población de 2010 y tasas de crecimiento para nuestro calculo 
data = {
    'Comuna': ['Comuna 13', 'Comuna 14', 'Comuna 12', 'Comuna 4', 'Comuna 1', 'Comuna 7', 'Comuna 8', 'Comuna 6', 'Comuna 11', 'Comuna 15', 'Comuna 3', 'Comuna 5', 'Comuna 10', 'Comuna 9', 'Comuna 2'],
    'Poblacion 2010': [231331, 225970, 200116, 218245, 205886, 220591, 187237, 176076, 189832, 182574, 187537, 179005, 166022, 161797, 157932],
    'Crecimiento 2010-2022': [14.64, 10.19, 18.07, 5.81, 8.44, -1.70, 9.40, 15.73, 7.19, 8.39, 4.22, 8.29, 3.47, 4.78, 0.27]
}

df_poblacion= pd.DataFrame(data)

# convertimos tasas de crecimiento en factores de crecimiento
df_poblacion['Factor de crecimiento']= 1 + df_poblacion['Crecimiento 2010-2022'] / 100

# calculamos la poblacion por cada año
for year in range(2016, 2022):
    n= year - 2010
    df_poblacion[f'Poblacion {year}']= df_poblacion['Poblacion 2010'] * df_poblacion['Factor de crecimiento']**(n/12)

df_poblacion

,Comuna,Poblacion 2010,Crecimiento 2010-2022,Factor de crecimiento,Poblacion 2016,Poblacion 2017,Poblacion 2018,Poblacion 2019,Poblacion 2020,Poblacion 2021
0,Comuna 13,231331,14.64,1.1464,247686.264822,250522.424102,253391.059141,256292.541807,259227.248224,262195.558826
1,Comuna 14,225970,10.19,1.1019,237203.928356,239129.813827,241071.335779,243028.621166,245001.797975,246990.995229
2,Comuna 12,200116,18.07,1.1807,217446.086117,220476.966723,223550.093374,226666.054919,229825.448413,233028.879235
3,Comuna 4,218245,5.81,1.0581,224495.510321,225554.529496,226618.544413,227687.578638,228761.655849,229840.799836
4,Comuna 1,205886,8.44,1.0844,214398.415091,215850.982427,217313.391029,218785.707572,220267.999184,221760.333447
5,Comuna 7,220591,-1.70,0.9830,218707.939187,218395.662249,218083.831189,217772.445369,217461.504154,217151.006909
6,Comuna 8,187237,9.40,1.0940,195839.519558,197311.218479,198793.976954,200287.878093,201793.005632,203309.443935
7,Comuna 6,176076,15.73,1.1573,189418.825818,191738.931523,194087.455157,196464.744796,198871.152783,201307.035776
8,Comuna 11,189832,7.19,1.0719,196538.011991,197678.489874,198825.585764,199979.338063,201139.785398,202306.966618
9,Comuna 15,182574,8.39,1.0839,190078.737500,191359.182404,192648.252886,193946.007054,195252.503402,196567.800821
10,Comuna 3,187537,4.22,1.0422,191453.142314,192113.737538,192776.612098,193441.773859,194109.230712,194778.990577
11,Comuna 5,179005,8.29,1.0829,186277.044528,187517.455650,188766.126618,190023.112434,191288.468466,192562.250452
12,Comuna 10,166022,3.47,1.0347,168877.917886,169358.657853,169840.766329,170324.247209,170809.104400,171295.341821
13,Comuna 9,161797,4.78,1.0478,165618.810759,166264.498990,166912.704528,167563.437187,168216.706818,168872.523312
14,Comuna 2,157932,0.27,1.0027,158145.064478,158180.603160,158216.149828,158251.704485,158287.267131,158322.837769

cambiamos tipo de dato de las columnas especificas a int64

In [9]:
# columnas de años a modificar
columnas_a_modificar= ['Poblacion 2016', 'Poblacion 2017', 'Poblacion 2018', 'Poblacion 2019', 'Poblacion 2020', 'Poblacion 2021' ]

# cambiamos tipo de dato a int64
for columna in columnas_a_modificar:
    df_poblacion[columna]= df_poblacion[columna].astype('int64')

In [10]:
df_poblacion.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Comuna                 15 non-null     object
 1   Poblacion 2010         15 non-null     int64
 2   Crecimiento 2010-2022  15 non-null     float64
 3   Factor de crecimiento  15 non-null     float64
 4   Poblacion 2016         15 non-null     int64
 5   Poblacion 2017         15 non-null     int64
 6   Poblacion 2018         15 non-null     int64
 7   Poblacion 2019         15 non-null     int64
 8   Poblacion 2020         15 non-null     int64
 9   Poblacion 2021         15 non-null     int64
dtypes: float64(2), int64(7), object(1)
memory usage: 1.3+ KB

procedemos a eliminar la columna 'Factor de crecimiento' ya que no sera necesaria

In [11]:
# eliminamos columna
df_poblacion= df_poblacion.drop(columns=['Factor de crecimiento'])

modificamos la columna 'Comuna' con el proposito de cambiar su tipo de dato

In [12]:
# modificamos columna
df_poblacion['Comuna']= df_poblacion['Comuna'].str.replace('Comuna', '')

# cambiamos tipo de dato a int64
df_poblacion['Comuna']= df_poblacion['Comuna'].astype('int64')

df_poblacion.head()

,Comuna,Poblacion 2010,Crecimiento 2010-2022,Poblacion 2016,Poblacion 2017,Poblacion 2018,Poblacion 2019,Poblacion 2020,Poblacion 2021
0,13,231331,14.64,247686,250522,253391,256292,259227,262195
1,14,225970,10.19,237203,239129,241071,243028,245001,246990
2,12,200116,18.07,217446,220476,223550,226666,229825,233028
3,4,218245,5.81,224495,225554,226618,227687,228761,229840
4,1,205886,8.44,214398,215850,217313,218785,220267,221760

# guardamos dataframe en archivo csv

In [13]:
df_poblacion.to_csv('data/poblacionCABA.csv')